import os
import re
from pathlib import Path
from typing import Optional, List, Dict, Any
from fastapi import APIRouter, HTTPException
from pydantic import BaseModel
from fs.router import SERVER_STORAGE_DIR, set_workspace, SetWorkspaceRequest
from ai.manager import model_manager
from ai.registry import model_registry
from ai.planner.dispatcher import save_generated_files
from ai.core.logger import logger

router = APIRouter(prefix="/ai", tags=["AI Prototype"])

class GeneratePrototypeRequest(BaseModel):
    name: str
    template: Optional[str] = "react"
    prompt: str
    api_key: Optional[str] = None
    plan: Optional[Dict[str, Any]] = None

def generate_fallback_prototype(name: str, template: str, prompt: str, target_dir: Path) -> List[str]:
    """Generates a rich, working prototype tailored to the user's prompt."""
    created_files = []
    
    clean_title = name.replace("-", " ").title()
    desc = prompt or f"A modern {template} application built with NovaDesk AI."

    if template == "react":
        files = {
            "package.json": f'''{{
  "name": "{name}",
  "private": true,
  "version": "0.1.0",
  "type": "module",
  "scripts": {{
    "dev": "vite",
    "build": "vite build",
    "preview": "vite preview"
  }},
  "dependencies": {{
    "react": "^18.3.1",
    "react-dom": "^18.3.1",
    "lucide-react": "^0.344.0"
  }},
  "devDependencies": {{
    "@vitejs/plugin-react": "^4.2.1",
    "vite": "^5.1.6"
  }}
}}''',
            "index.html": f'''<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{clean_title} | NovaDesk Prototype</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&display=swap" rel="stylesheet">
    <style>
      body {{ font-family: 'Inter', sans-serif; }}
    </style>
  </head>
  <body class="bg-slate-950 text-slate-100 min-h-screen">
    <div id="root"></div>
    <script type="module" src="/src/main.jsx"></script>
  </body>
</html>''',
            "vite.config.js": '''import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';

export default defineConfig({
  plugins: [react()],
});''',
            "src/main.jsx": '''import React from 'react';
import ReactDOM from 'react-dom/client';
import App from './App.jsx';
import './index.css';

ReactDOM.createRoot(document.getElementById('root')).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);''',
            "src/index.css": '''@keyframes pulse-slow {
  0%, 100% { opacity: 0.3; }
  50% { opacity: 0.6; }
}
.animate-glow {
  animation: pulse-slow 4s ease-in-out infinite;
}''',
            "src/App.jsx": f'''import React, {{ useState }} from 'react';
import {{ Header }} from './components/Header.jsx';
import {{ Dashboard }} from './components/Dashboard.jsx';
import {{ AnalyticsChart }} from './components/AnalyticsChart.jsx';
import {{ ItemList }} from './components/ItemList.jsx';

export default function App() {{
  const [activeTab, setActiveTab] = useState('overview');

  return (
    <div className="min-h-screen bg-slate-950 text-slate-100 flex flex-col">
      <Header title="{clean_title}" activeTab={{activeTab}} setActiveTab={{setActiveTab}} />
      
      <main className="flex-1 max-w-7xl w-full mx-auto px-6 py-8 flex flex-col gap-8">
        {{/* Hero / Prompt Banner */}}
        <div className="relative overflow-hidden rounded-2xl border border-white/10 bg-gradient-to-r from-blue-900/40 via-indigo-900/30 to-purple-900/40 p-8 backdrop-blur-xl">
          <div className="relative z-10 max-w-2xl">
            <span className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full text-xs font-semibold bg-emerald-500/20 text-emerald-400 border border-emerald-500/30 mb-3">
              ✨ AI Prototype Generated
            </span>
            <h1 className="text-3xl font-extrabold tracking-tight text-white mb-2">{clean_title}</h1>
            <p className="text-slate-300 text-sm leading-relaxed">{desc}</p>
          </div>
          <div className="absolute right-[-10%] top-[-30%] w-80 h-80 rounded-full bg-blue-500/20 filter blur-3xl animate-glow pointer-events-none" />
        </div>

        {{/* Dashboard Metrics */}}
        <Dashboard />

        {{/* Charts and Items Grid */}}
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
          <div className="lg:col-span-2">
            <AnalyticsChart />
          </div>
          <div>
            <ItemList />
          </div>
        </div>
      </main>

      <footer className="border-t border-white/5 py-6 text-center text-xs text-slate-500">
        Generated by NovaDesk AI Studio &bull; Ready for deployment
      </footer>
    </div>
  );
}}''',
            "src/components/Header.jsx": '''import React from 'react';

export function Header({ title, activeTab, setActiveTab }) {
  const tabs = ['overview', 'analytics', 'activity', 'settings'];

  return (
    <header className="border-b border-white/10 bg-slate-900/80 backdrop-blur-md sticky top-0 z-50">
      <div className="max-w-7xl mx-auto px-6 h-16 flex items-center justify-between">
        <div className="flex items-center gap-3">
          <div className="w-8 h-8 rounded-lg bg-gradient-to-tr from-blue-600 to-emerald-400 flex items-center justify-center font-bold text-white shadow-lg shadow-blue-500/30">
            N
          </div>
          <span className="font-bold text-lg tracking-tight text-white">{title}</span>
        </div>

        <nav className="flex items-center gap-1">
          {tabs.map((tab) => (
            <button
              key={tab}
              onClick={() => setActiveTab(tab)}
              className={`capitalize px-3 py-1.5 rounded-lg text-xs font-medium transition-all ${
                activeTab === tab
                  ? 'bg-white/15 text-white shadow-sm'
                  : 'text-slate-400 hover:text-slate-200 hover:bg-white/5'
              }`}
            >
              {tab}
            </button>
          ))}
        </nav>
      </div>
    </header>
  );
}''',
            "src/components/Dashboard.jsx": '''import React from 'react';

export function Dashboard() {
  const stats = [
    { label: 'Active Users', value: '14,820', change: '+12.4%', isPositive: true },
    { label: 'Total Volume', value: '$84,230', change: '+8.1%', isPositive: true },
    { label: 'Conversion Rate', value: '3.42%', change: '-0.3%', isPositive: false },
    { label: 'Response Latency', value: '42ms', change: '-5ms', isPositive: true },
  ];

  return (
    <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
      {stats.map((s, i) => (
        <div key={i} className="p-5 rounded-xl border border-white/10 bg-white/5 backdrop-blur-lg flex flex-col gap-2 shadow-sm hover:border-white/20 transition">
          <span className="text-xs text-slate-400 font-medium">{s.label}</span>
          <div className="flex items-baseline justify-between">
            <span className="text-2xl font-bold tracking-tight text-white">{s.value}</span>
            <span className={`text-xs font-semibold px-2 py-0.5 rounded-full ${s.isPositive ? 'text-emerald-400 bg-emerald-500/10' : 'text-rose-400 bg-rose-500/10'}`}>
              {s.change}
            </span>
          </div>
        </div>
      ))}
    </div>
  );
}''',
            "src/components/AnalyticsChart.jsx": '''import React from 'react';

export function AnalyticsChart() {
  const bars = [40, 65, 50, 85, 95, 75, 60, 90, 110, 100, 125, 140];
  const months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];

  return (
    <div className="p-6 rounded-2xl border border-white/10 bg-white/5 backdrop-blur-lg h-full flex flex-col justify-between">
      <div className="flex items-center justify-between mb-6">
        <div>
          <h3 className="text-base font-semibold text-white">Performance Overview</h3>
          <p className="text-xs text-slate-400">Monthly activity trends</p>
        </div>
        <span className="text-xs font-medium px-3 py-1 rounded-md bg-blue-500/20 text-blue-400 border border-blue-500/30">
          Live Real-time
        </span>
      </div>

      <div className="flex items-end gap-3 h-48 pt-6">
        {bars.map((height, i) => (
          <div key={i} className="flex-1 flex flex-col items-center gap-2 group">
            <div
              className="w-full rounded-t-md bg-gradient-to-t from-blue-600 to-indigo-400 group-hover:from-blue-500 group-hover:to-cyan-300 transition-all duration-300"
              style={{ height: `${(height / 150) * 100}%` }}
            />
            <span className="text-[10px] text-slate-500">{months[i]}</span>
          </div>
        ))}
      </div>
    </div>
  );
}''',
            "src/components/ItemList.jsx": '''import React from 'react';

export function ItemList() {
  const items = [
    { title: 'Project Initialization', time: 'Just now', status: 'Completed' },
    { title: 'Database Migration', time: '2m ago', status: 'In Progress' },
    { title: 'OAuth Provider Link', time: '14m ago', status: 'Completed' },
    { title: 'API Webhook Verification', time: '1h ago', status: 'Verified' },
  ];

  return (
    <div className="p-6 rounded-2xl border border-white/10 bg-white/5 backdrop-blur-lg flex flex-col gap-4">
      <h3 className="text-base font-semibold text-white">Recent Activities</h3>
      <div className="flex flex-col divide-y divide-white/5">
        {items.map((item, i) => (
          <div key={i} className="py-3 flex items-center justify-between">
            <div>
              <p className="text-xs font-medium text-slate-200">{item.title}</p>
              <span className="text-[10px] text-slate-500">{item.time}</span>
            </div>
            <span className="text-[10px] font-semibold text-emerald-400 bg-emerald-500/10 px-2 py-0.5 rounded-full">
              {item.status}
            </span>
          </div>
        ))}
      </div>
    </div>
  );
}''',
            "README.md": f'''# {clean_title}

Prototype generated with **NovaDesk AI Studio**.

## Prompt:
> {prompt}

## Running Locally:
```bash
npm install
npm run dev
```
'''
        }
    elif template == "nextjs" or template == "next":
        files = {
            "package.json": f'''{{
  "name": "{name}",
  "version": "0.1.0",
  "private": true,
  "scripts": {{
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  }},
  "dependencies": {{
    "next": "^15.1.0",
    "react": "^19.0.0",
    "react-dom": "^19.0.0",
    "lucide-react": "^0.460.0",
    "clsx": "^2.1.1",
    "tailwind-merge": "^2.5.5"
  }},
  "devDependencies": {{
    "@types/node": "^22.0.0",
    "@types/react": "^19.0.0",
    "@types/react-dom": "^19.0.0",
    "typescript": "^5.6.0",
    "tailwindcss": "^3.4.16",
    "postcss": "^8.4.49",
    "autoprefixer": "^10.4.20"
  }}
}}''',
            "next.config.mjs": '''/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
};

export default nextConfig;''',
            "tailwind.config.js": '''/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
      },
    },
  },
  plugins: [],
};''',
            "postcss.config.js": '''module.exports = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
};''',
            "tsconfig.json": '''{
  "compilerOptions": {
    "target": "ES2022",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "plugins": [{ "name": "next" }],
    "paths": { "@/*": ["./*"] }
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
  "exclude": ["node_modules"]
}''',
            "app/globals.css": '''@tailwind base;
@tailwind components;
@tailwind utilities;

:root {
  --background: #030712;
  --foreground: #f8fafc;
}

body {
  color: var(--foreground);
  background: var(--background);
  font-family: system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, sans-serif;
}''',
            "app/layout.tsx": f'''import type {{ Metadata }} from 'next';
import './globals.css';

export const metadata: Metadata = {{
  title: '{clean_title} | NovaDesk Fullstack',
  description: '{desc}',
}};

export default function RootLayout({{
  children,
}}: Readonly<{{
  children: React.ReactNode;
}}>) {{
  return (
    <html lang="en" className="dark">
      <body className="min-h-screen bg-[#030712] text-slate-100 antialiased selection:bg-lime-400 selection:text-black">
        {{children}}
      </body>
    </html>
  );
}}''',
            "app/page.tsx": f'''import Link from 'next/link';
import {{ Sparkles, Terminal, Cpu, ArrowUpRight, CheckCircle2, Layers }} from 'lucide-react';

export default function HomePage() {{
  const features = [
    {{ title: 'Next.js 15 App Router', desc: 'Server components, streaming SSR, and edge-ready API routes.', badge: 'Framework' }},
    {{ title: 'Google Gemini 2.5 Intelligence', desc: 'Code synthesized and maintained by Google Gemini AI models.', badge: 'AI-Native' }},
    {{ title: 'WebSocket Real-time Engine', desc: 'Zero-latency live state updates and event broadcasting.', badge: 'Live Stream' }},
    {{ title: 'Tailwind CSS & Glassmorphism', desc: 'Crafted with modern responsive design and dark aesthetics.', badge: 'Design' }},
  ];

  return (
    <main className="flex min-h-screen flex-col items-center justify-between p-8 md:p-16 max-w-6xl mx-auto">
      <div className="z-10 w-full flex items-center justify-between font-mono text-sm border-b border-white/10 pb-6">
        <div className="flex items-center gap-2">
          <div className="w-8 h-8 rounded-lg bg-gradient-to-tr from-lime-400 to-emerald-500 flex items-center justify-center text-black font-bold">
            N
          </div>
          <span className="font-bold tracking-tight text-white">{clean_title}</span>
          <span className="text-[10px] px-2 py-0.5 rounded-full bg-lime-400/10 text-lime-300 border border-lime-400/20">Next.js 15 Fullstack</span>
        </div>
        <div className="hidden sm:flex items-center gap-3 text-xs text-slate-400">
          <span className="w-2 h-2 rounded-full bg-emerald-400 animate-pulse" />
          <span>Status: Live Sandbox</span>
        </div>
      </div>

      <div className="relative flex flex-col items-center text-center my-16 gap-6">
        <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full bg-white/5 border border-white/10 text-xs text-lime-400 backdrop-blur-md">
          <Sparkles size={{14}} />
          <span>Synthesized by NovaDesk AI</span>
        </div>
        <h1 className="text-4xl md:text-6xl font-extrabold tracking-tight text-white max-w-3xl">
          {clean_title}
        </h1>
        <p className="text-base md:text-lg text-slate-400 max-w-2xl leading-relaxed">
          {desc}
        </p>

        <div className="flex items-center gap-4 mt-4">
          <a
            href="/api/data"
            target="_blank"
            className="flex items-center gap-2 px-5 py-2.5 rounded-xl bg-gradient-to-r from-lime-400 to-emerald-500 text-black font-semibold text-xs shadow-lg shadow-lime-500/20 hover:scale-[1.02] transition"
          >
            <span>Test API Route</span>
            <ArrowUpRight size={{14}} />
          </a>
          <button className="flex items-center gap-2 px-5 py-2.5 rounded-xl bg-white/5 hover:bg-white/10 text-white font-semibold text-xs border border-white/10 transition">
            <Terminal size={{14}} />
            <span>npm run dev</span>
          </button>
        </div>
      </div>

      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4 w-full">
        {{features.map((f, i) => (
          <div key={{i}} className="p-6 rounded-2xl bg-white/[0.03] border border-white/10 hover:border-lime-400/30 transition-all flex flex-col justify-between gap-4">
            <span className="text-[10px] uppercase font-bold tracking-wider text-lime-400 bg-lime-400/10 px-2.5 py-1 rounded-md w-fit border border-lime-400/20">
              {{f.badge}}
            </span>
            <div>
              <h3 className="text-base font-bold text-white mb-1">{{f.title}}</h3>
              <p className="text-xs text-slate-400 leading-relaxed">{{f.desc}}</p>
            </div>
            <div className="flex items-center gap-1.5 text-xs text-emerald-400 font-medium pt-2 border-t border-white/5">
              <CheckCircle2 size={{13}} />
              <span>Operational</span>
            </div>
          </div>
        ))}}
      </div>

      <footer className="mt-16 text-xs text-slate-500 flex items-center justify-between w-full border-t border-white/5 pt-6">
        <span>Prompt: "{prompt}"</span>
        <span>NovaDesk AI Cloud Architecture</span>
      </footer>
    </main>
  );
}}''',
            "app/api/data/route.ts": f'''import {{ NextResponse }} from 'next/server';

export async function GET() {{
  return NextResponse.json({{
    project: "{clean_title}",
    framework: "Next.js 15 App Router",
    ai_engine: "Google Gemini 2.5 Flash",
    status: "ok",
    timestamp: new Date().toISOString(),
    endpoints: [
      {{ path: "/api/data", method: "GET", description: "Sample REST route" }}
    ]
  }});
}}''',
            "README.md": f'''# {clean_title}

Full-Stack Next.js 15 application generated with **NovaDesk AI Studio** (powered by Google Gemini 2.5).

## Prompt:
> {prompt}

## Features:
- Next.js 15 App Router (`app/layout.tsx`, `app/page.tsx`)
- API Route Handlers (`app/api/data/route.ts`)
- TypeScript & Tailwind CSS
- Zero-dependency cloud execution

## Development:
```bash
npm install
npm run dev
```
'''
        }
    elif template == "python":
        files = {
            "main.py": f'''from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from typing import List, Optional

app = FastAPI(title="{clean_title}", description="{desc}")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

class Item(BaseModel):
    id: int
    name: str
    description: Optional[str] = None
    completed: bool = False

database: List[Item] = [
    Item(id=1, name="Initialize project", description="Generated by NovaDesk AI", completed=True),
    Item(id=2, name="Implement API routes", description="REST endpoints ready", completed=True),
    Item(id=3, name="Connect frontend", description="Connect to web client", completed=False),
]

@app.get("/")
def read_root():
    return {{"status": "online", "project": "{clean_title}", "docs": "/docs"}}

@app.get("/items", response_model=List[Item])
def get_items():
    return database

@app.post("/items", response_model=Item)
def create_item(item: Item):
    database.append(item)
    return item

if __name__ == "__main__":
    import uvicorn
    uvicorn.run("main:app", host="0.0.0.0", port=8000, reload=True)
''',
            "requirements.txt": '''fastapi==0.115.6
uvicorn==0.34.0
pydantic==2.10.4
''',
            "README.md": f'''# {clean_title}

Python FastAPI service generated with **NovaDesk AI Studio**.

## Prompt:
> {prompt}

## Running:
```bash
pip install -r requirements.txt
python main.py
```
View interactive documentation at `http://localhost:8000/docs`.
'''
        }
    else:
        # Fullstack HTML/CSS/JS starter
        files = {
            "index.html": f'''<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{clean_title}</title>
  <link rel="stylesheet" href="style.css">
  <script src="https://cdn.tailwindcss.com"></script>
</head>
<body class="bg-slate-950 text-slate-100 min-h-screen p-8 flex flex-col items-center">
  <main class="max-w-3xl w-full flex flex-col gap-6">
    <header class="border-b border-white/10 pb-6">
      <span class="text-xs font-bold text-emerald-400 uppercase tracking-wider">AI Prototype</span>
      <h1 class="text-4xl font-extrabold text-white mt-1">{clean_title}</h1>
      <p class="text-slate-400 mt-2">{desc}</p>
    </header>

    <div class="p-6 rounded-2xl border border-white/10 bg-white/5 backdrop-blur-xl flex flex-col gap-4">
      <h2 class="text-lg font-bold text-white">Interactive Demo</h2>
      <div class="flex gap-2">
        <input id="demo-input" type="text" placeholder="Add a new item..." class="flex-1 bg-black/40 border border-white/10 rounded-lg px-4 py-2 text-sm outline-none focus:border-blue-500">
        <button id="add-btn" class="bg-blue-600 hover:bg-blue-500 text-white font-semibold px-4 py-2 rounded-lg text-sm transition">Add</button>
      </div>
      <ul id="item-list" class="flex flex-col gap-2 mt-4">
        <li class="p-3 bg-white/5 rounded-lg text-sm border border-white/5 flex items-center justify-between">
          <span>Explore generated prototype code</span>
          <span class="text-xs text-emerald-400">Ready</span>
        </li>
      </ul>
    </div>
  </main>
  <script src="script.js"></script>
</body>
</html>''',
            "style.css": '''/* Custom styles */
body {
  font-family: system-ui, -apple-system, sans-serif;
}
''',
            "script.js": '''document.addEventListener('DOMContentLoaded', () => {
  const input = document.getElementById('demo-input');
  const btn = document.getElementById('add-btn');
  const list = document.getElementById('item-list');

  btn.addEventListener('click', () => {
    const val = input.value.trim();
    if (!val) return;
    const li = document.createElement('li');
    li.className = 'p-3 bg-white/5 rounded-lg text-sm border border-white/5 flex items-center justify-between';
    li.innerHTML = `<span>${val}</span><span class="text-xs text-blue-400">New</span>`;
    list.appendChild(li);
    input.value = '';
  });
});''',
            "README.md": f'''# {clean_title}

Web Prototype generated by NovaDesk AI Studio.

## Prompt:
> {prompt}
'''
        }

    for rel_path, content in files.items():
        file_path = target_dir / rel_path
        file_path.parent.mkdir(parents=True, exist_ok=True)
        file_path.write_text(content, encoding="utf-8")
        created_files.append(rel_path)

    return created_files

@router.post("/prototype")
async def generate_prototype(req: GeneratePrototypeRequest):
    """Generates a complete project prototype from user prompt and stack."""
    clean_name = req.name.strip().replace(" ", "-").lower()
    if not clean_name:
        clean_name = "ai-prototype"

    target_dir = SERVER_STORAGE_DIR / clean_name
    if target_dir.exists():
        import time
        clean_name = f"{clean_name}-{int(time.time())}"
        target_dir = SERVER_STORAGE_DIR / clean_name

    target_dir.mkdir(parents=True, exist_ok=True)

    files_created = []

    # Attempt to use AI model if accessible
    ai_succeeded = False
    try:
        target_model = model_registry.get_unified_model()
        plan_context = ""
        if req.plan:
            tasks_summary = ", ".join([f"{t.get('id')}: {t.get('title')}" for t in req.plan.get("tasks", [])])
            plan_context = f"\nExecution Plan Blueprint:\nTasks: {tasks_summary}\nArchitecture: {req.plan.get('architecture', {})}\n"

        system_prompt = (
            f"You are an expert fullstack software architect. "
            f"Generate a working, complete prototype for a {req.template} project called '{clean_name}'. "
            f"User request: {req.prompt}\n{plan_context}\n"
            f"For every file you generate, output: `### File: relative/path/to/file.ext` followed by a markdown code block with the full file code.\n"
            f"Generate all necessary files including package.json/requirements.txt, entrypoint, components, styling, and README.md."
        )
        messages = [{"role": "user", "content": system_prompt}]
        
        full_text = []
        call_kwargs = {}
        if req.api_key and req.api_key.strip():
            call_kwargs["api_key"] = req.api_key.strip()

        async for chunk in model_manager.stream(messages, target_model.id, **call_kwargs):
            full_text.append(chunk)

        combined = "".join(full_text)
        saved = save_generated_files(combined, str(target_dir), req.prompt)
        if saved:
            files_created = [f["path"] for f in saved]
            ai_succeeded = True
            logger.info(f"AI generated {len(saved)} prototype files for {clean_name}")
    except Exception as e:
        logger.warning(f"AI streaming prototype generation fallback: {e}")

    if not ai_succeeded or not files_created:
        # Fallback to intelligent scaffold tailored to prompt & template
        files_created = generate_fallback_prototype(clean_name, req.template, req.prompt, target_dir)

    # Set as active codespace
    await set_workspace(SetWorkspaceRequest(rootPath=str(target_dir)))

    return {
        "ok": True,
        "name": clean_name,
        "path": str(target_dir),
        "template": req.template,
        "files": files_created,
        "message": f"Successfully created {len(files_created)} files for {clean_name}."
    }
