"""remove quotas and selected_model

Revision ID: 037b56ba21fc
Revises: 3a5879a3680c
Create Date: 2026-07-28 22:55:33.883276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '037b56ba21fc'
down_revision: Union[str, None] = '3a5879a3680c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_daily_quotas_date', table_name='daily_quotas')
    op.drop_index('ix_daily_quotas_id', table_name='daily_quotas')
    op.drop_table('daily_quotas')
    op.drop_column('conversations', 'selected_model')
    op.drop_column('users', 'selected_ai_model')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('selected_ai_model', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('conversations', sa.Column('selected_model', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_table('daily_quotas',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('credits_used', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='daily_quotas_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='daily_quotas_pkey')
    )
    op.create_index('ix_daily_quotas_id', 'daily_quotas', ['id'], unique=False)
    op.create_index('ix_daily_quotas_date', 'daily_quotas', ['date'], unique=False)
    # ### end Alembic commands ###
