"""replace google_id with hashed_password

Revision ID: 3a5879a3680c
Revises: d7430fae43c3
Create Date: 2026-07-28 22:46:11.489190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a5879a3680c'
down_revision: Union[str, None] = 'd7430fae43c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', sa.String(), nullable=True))
    op.drop_index('ix_users_google_id', table_name='users')
    op.drop_column('users', 'google_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('google_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_users_google_id', 'users', ['google_id'], unique=True)
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###
